apiVersion: "installer.kyma-project.io/v1alpha1"
kind: Installation
metadata:
  name: kyma-installation
  finalizers:
    - finalizer.installer.kyma-project.io
spec:
  version: ""
  url: ""
  components: 
    - name: "knative"
     namespace: "default"
    # - name: "legacy"
    #   namespace: "default"
    - name: "modified"
      namespace: "default"
    - name: "unchanged"
      namespace: "default"
